services:
 nginx:
  image: nginx:alpine
  container_name: nginx
  ports:
   - 80:80
  volumes:
   - ./nginx.conf:/etc/nginx/nginx.conf
  depends_on:
   - nextjs
      
 nextjs:
  container_name: nextjs
  build:
   context: .
  environment:
   NODE_ENV: production
  ports:
   - 3000:3000